site_name: MLup
site_url: https://mlup.org/

repo_url: https://github.com/nxexox/pymlup
repo_name: PyMLup

theme:
  name: material
  language: en
  custom_dir: docs
  logo: assets/img/logo_without_text.png
  features:
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
    - offline
  favicon: assets/img/favicon.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: "teal"
#      accent: "cyan"
      accent: 485edf

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#      primary: "cyan"
      primary: 485edf
      accent: "teal"

extra:
  homepage: https://mlup.org
  analytics:
    provider: custom
  version:
    provider: mike
    default: stable
