version: '1'
ml:
  auto_detect_predict_params: true
  binarization_type: mlup.ml.binarization.pickle.PickleBinarizer
  columns:
    - default: 1.4
      name: MinTemp
      required: false
      type: float
    - name: MaxTemp
      required: false
      type: float
    - name: Humidity9am
      required: false
      type: float
    - name: Humidity3pm
      required: false
      type: float
    - name: Pressure9am
      required: false
      type: float
    - name: Pressure3pm
      required: false
      type: float
    - name: Temp9am
      required: false
      type: float
    - name: Temp3pm
      required: false
      type: float
  data_transformer_for_predict: mlup.ml.data_transformers.pandas_data_transformer.PandasDataFrameTransformer
  data_transformer_for_predicted: mlup.ml.data_transformers.numpy_data_transformer.NumpyDataTransformer
  dtype_for_predict: null
  max_thread_loop_workers: null
  name: MyName
  predict_method_name: predict
  storage_kwargs:
    files_mask: scikit-learn-binary_cls_model.pckl
    path_to_files: models/scikit-learn-binary_cls_model.pckl
  storage_type: mlup.ml.storage.local_disk.DiskStorage
  type: sklearn
  use_thread_loop: false
  version: MyVersion
web:
  batch_worker_timeout: 1.0
  column_validation: false
  debug: false
  host: 0.0.0.0
  is_long_predict: false
  item_id_col_name: mlup_item_id
  max_queue_size: 100
  min_batch_len: 10
  mode: mlup.web.architecture.directly_to_predict.DirectlyToPredictArchitecture
  port: 8009
  show_docs: true
  throttling_max_request_len: null
  throttling_max_requests: null
  timeout_for_shutdown_daemon: 3.0
  ttl_client_wait: 30.0
  ttl_predicted_data: 60
  uvicorn_kwargs: {}
  web_app_version: 1.0.0.0
