name: Deploy mkdocs with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
#    branches: ["main", "ci_docs"]
    branches: ["*"]
    paths:
      - "**.md"
      - "mkdocs.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-material
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy
