name: Docs

on:
  # Runs on pushes targeting the default branch
  # TODO: Add deploy by tag and make version from tag
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docs_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
      - run: pip install --upgrade pip && pip install mkdocs mkdocs-gen-files mkdocs-material
      - name: Deploy docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add gh-token "https://github.com/nxexox/pymlup.git"
          git fetch gh-token && git fetch gh-token gh-pages:gh-pages
          python -m mkdocs gh-deploy --clean -m "Deploying Docs to GitHub Pages (${GITHUB_SHA:0:7})" --remote-name gh-token
          git push gh-token gh-pages
